apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.136.104.98
  name: gke_hoffelix-kube_us-central1_hoffelix-kube-gke
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://35.199.57.83
  name: gke_wolfacid-qa_us-east4-a_cluster
contexts:
- context:
    cluster: gke_hoffelix-kube_us-central1_hoffelix-kube-gke
    user: gke_hoffelix-kube_us-central1_hoffelix-kube-gke
  name: gke_hoffelix-kube_us-central1_hoffelix-kube-gke
- context:
    cluster: gke_wolfacid-qa_us-east4-a_cluster
    user: gke_wolfacid-qa_us-east4-a_cluster
  name: gke_wolfacid-qa_us-east4-a_cluster
current-context: gke_hoffelix-kube_us-central1_hoffelix-kube-gke
kind: Config
preferences: {}
users:
- name: gke_hoffelix-kube_us-central1_hoffelix-kube-gke
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /Users/ahoffmann/Downloads/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_wolfacid-qa_us-east4-a_cluster
  user:
    auth-provider:
      config:
        access-token: ya29.a0ARrdaM969QglhAWCwmSIvQvLpsW93E846HZTploFWrbLwiimpCwIvN3LgsrHjX5DrNGtHsjDCE6__yq-Hb-nHROUrTmrmLIN_wsyYZ0ygbZ5vh9_9WklKpyPSz9jQ0iLMTK7-73Wysieq_0uJaG96CWTDt6A8HIvLniwS9M
        cmd-args: config config-helper --format=json
        cmd-path: /Users/ahoffmann/Downloads/google-cloud-sdk/bin/gcloud
        expiry: "2021-07-19T17:01:37Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp